### ISSUE TITLE
Reduce delay between isLoading=false and sound actually playing

### ISSUE THREAD

**Issue by jkeen** [nypublicradio/ember-hifi#19]
I noticed this on wnyc.org (mobile) after the new release.

I hit play on my iPhone, saw the spinning animation indicating that isLoading=true, and then it turned to a play button but sat at `0:00` for a couple of seconds before it actually played. We should reduce this to as close to zero as possible.

**Comment by noslouch** [comment]
this might be fixed by d2d8121b83ccf31964e3faf2eae2c44547bc294f. can you check again?

**Comment by jkeen** [comment]
It's still an issue, but I'm not sure if it's fixable. The audio element is telling us it's playing, but it's really not. It's still loading. It knows it *can* play, it knows it *will* play, but it's not playing right then.

So I will close this
