### ISSUE TITLE
application.register is not a function / Ember 1.13 compatibility?

### ISSUE THREAD

**Issue by sparkrevolutions** [nypublicradio/ember-hifi#21]
Really interested in using this plugin, however most of our projects run on Ember 1.13 and after installation we get a ```javascript application.register is not a function``` when launching our apps.

Is the project compatible with Ember 1.13.13?

**Comment by noslouch** [comment]
Hm. It [passes for ember-1.13](https://circleci.com/gh/nypublicradio/ember-hifi/120) in automated testing. Can you create a twiddle or jsbin reproducing the problem?

**Comment by noslouch** [comment]
bump

**Comment by noslouch** [comment]
closing this for now. feel free to reopen with a reduced test case.

**Comment by sparkrevolutions** [comment]
Hi @noslouch. Sorry, been super busy.

I'll put something together for you over the weekend.

Thanks for getting back to me!
