### ISSUE TITLE
Component for position control?

### ISSUE THREAD

**Issue by jessepollak** [nypublicradio/ember-hifi#28]
This is more of a question than an issue: in y'alls use case, have you written your own custom position control? If so, are you using any libraries or tools to help make that easier? I'm investigating writing one but want to make sure I don't do any duplicate work.

**Comment by jkeen** [comment]
Yeah, WNYC does use their own custom made position control for their player (and it's a little involved), but we're wrapping up some work to break off the whole WNYC player into its own ember addon that *might* get open sourced… so you might not have to reinvent the wheel. Not 100% sure on the timing of that, though. @noslouch would have a better idea on that

**Comment by jkeen** [comment]
@jessepollak https://github.com/nypublicradio/nypr-player

Open sourced, see if that helps you out.

**Comment by jessepollak** [comment]
awesome, thank you so much!
