### ISSUE TITLE
Error in IE - URL Promise failed because: All given promises failed.

### ISSUE THREAD

**Issue by Aaronfischer** [nypublicradio/ember-hifi#36]
So obviously this is working in chrome/firefox/safari, but in IE (tested Edge 13/14) when attempting to play I get the error: `URL Promise failed because: All given promises failed.`

Here is the basic gist of what were doing:
```js
// component
export default Ember.Component.extend({
  hifi: Ember.inject.service(),
  tagName: '',
  url: null,
  actions: {
    play(urls) {
      this.get('hifi').play(urls).then(() => {
        // sound object
      });
    },
    pause() {
      this.get('hifi').togglePause();
    },
  },
});
```

```hbs
{{!-- simply pass in the url of the audio relationship --}}
{{app-audio url=model.audio.url}}
```

I've checked both if `audio.url` is sideloaded on route refresh and also if it is a promise on transition and both still throw the error in IE.

**Comment by jkeen** [comment]
Try turning on the debug flag in the environment settings: 

```javascript
emberHifi: {
   debug: true
}
```
and see what that spits out. I've been meaning to improve that default error message with some more descriptive failures. You can also get details about the failures if you add a `catch` to that `play` promise like so: 

```javascript
this.get('hifi').play(urls).then(() => {
      // sound object
 }).catch(({failures}) => {
     console.log(failures)
})
```

**Comment by Aaronfischer** [comment]
@jkeen That looks like it'll be super helpful, thanks! I'll try this out.

I did want to report, I tried a different .wav file and it actually played fine in IE 13/14. So I'm assuming the other must have been some kind of corrupt (or who really know... encoding issue?)

So I think the above issue is actually a non-issue, an error on my part.

I did have 1 more question to piggyback, what format does ember-hifi (looks like the base.js) for the mime type? I'm recording then pushing a blob into hifi and in Chrome it plays fine but with a warning that it cant determine the mime type. 
The blob:
```js
{
  name: "Recorded Audio",
  size: 327724,
  type: "audio/wav"
}
```

Thanks!

**Comment by jkeen** [comment]
@Aaronfischer Ah alright, good to know. It tries to detect the mime-type off of the file extension, and if there isn't one specified you should pass it in as an option when you're playing that blob. Instead of passing a string or an array of strings into `play` or `load`, pass in a hash or array of hashes with `url` and `mimeType` specified, like so: 

```javascript
this.get('hifi').play([{url: blob, mimeType: mimeType}]).then(() => {
   // sound object
});
```

**Comment by noslouch** [comment]
one day we'll have a great dummy app with all these use cases

**Comment by Aaronfischer** [comment]
@jkeen Awesome, that was the ticket! 🥇 

@noslouch 👍 

Thanks guys!
