### ISSUE TITLE
Example of using 'Read Only Properties'?

### ISSUE THREAD

**Issue by davidchalifoux** [nypublicradio/ember-hifi#38]
I'm still somewhat of a beginner to Ember.js and I am simply confused as to exactly how to use the `'Read Only Properties'`. I'd love to get some sort of example.

I'm trying to build a toggleable play button that turns into a pause button if the sound is playing. Thanks!

**Comment by jkeen** [comment]
Sure, you can use those properties in a component to change state on UI elements, or do other things. For your example, something like this will change a button to have an `is-playing` class any time a sound is playing on hifi. 

```js
import service from 'ember-service/inject';
import computed from 'ember-computed';

export default Component.extend({
  hifi: service(),
  classNameBindings: ['isPlaying'],
  isPlaying: computed.reads('hifi.isPlaying')
})
```

To have each button scoped to a particular sound, you can look at the current sound and compare the urls (if you know the url at render time)

```js
import service from 'ember-service/inject';
import computed from 'ember-computed';

export default Component.extend({
  url: null, //passed in
  hifi: service(),
  classNameBindings: ['isPlaying'],
  currentSoundIsThisSound: computed.equals('hifi.currentSound.url', 'url'),
  currentSoundIsPlaying: computed.reads('hifi.isPlaying'),
  isPlaying: computed.and('currentSoundIsThisSound', 'currentSoundIsPlaying'),

  actions: {
     play() {
       let url = this.get('url');
       this.set('isLoading', true);
       this.get('hifi').play(url).then(({sound}) => {
          // sound is playing
       }).finally(() => this.set('isLoading', false));
     }
  }
});
```

Hope that clears things up!
