### ISSUE TITLE
Chrome autoplay issue

### ISSUE THREAD

**Issue by chrism** [nypublicradio/ember-hifi#51]
Hi,

Love this addon thanks for all your hard work!

I've been using it for a long time with no issues. Until!

It seems like [Google's new autoplay policy](https://developers.google.com/web/updates/2017/09/autoplay-policy-changes) has spoiled everything.

Chrome now fails and the console provides this error message

```
native-audio.js:307 Uncaught (in promise) DOMException: play() failed because the user didn't interact with the document first. https://goo.gl/xX8pDD
play @ native-audio.js:307
_attemptToPlaySound @ hifi.js:776
load.then @ hifi.js:258
tryCatcher @ rsvp.js:200
invokeCallback @ rsvp.js:372
publish @ rsvp.js:358
(anonymous) @ rsvp.js:14
invoke @ backburner.js:205
flush @ backburner.js:125
flush @ backburner.js:278
end @ backburner.js:410
_run @ backburner.js:760
run @ backburner.js:468
run @ ember-metal.js:408
$.on.e @ native-audio.js:46
dispatch @ jquery.js:5183
elemData.handle @ jquery.js:4991
```

I added a `catch` to my code hoping that this might let me handle the error like this:

```js
    this.get('hifi').play({ url: ENV.radioStreamUri, mimeType: 'audio/mpeg' })
    .catch(error => {
      console.log('error', error);
    })
``` 
But with no success.

I also noted that there seems to be some recent commits for better error handling and I wondered if you may have already fixed this issue.

After installing the addon from master (via `"ember-hifi": "nypublicradio/ember-hifi"`) the original error message disappeared but there still was no caught error message logged to the console.

Do you have a recommended way of handling this issue?

Many thanks!

**Comment by jkeen** [comment]
Sorry this has stagnated. Browsers have changed even more since this ticket was filed, and some updates have been made. If you're still having issues regarding this, please reopen!

**Comment by chrism** [comment]
No problem, thanks for letting me know!

I will give it a try and let you know. Perfect timing really tbh as I’d like to use this library again on a project I am working on but not sure if it was being actively maintained.

BTW If I run into any issues would PRs be accepted? I’d like to help if I can if you think you’d have the time to merge them etc.

**Comment by jkeen** [comment]
yeah for sure! I'm picking this back up again after letting it stagnate for a little too long. If you download the latest on master, you'll be able to make changes and do development on this library a little easier since there's now a diagnostic interface for playing audio/testing audio types. 

Just load up the dummy app and visit `/diagnostic`, or see it live [here](https://nypublicradio.github.io/ember-hifi/#/diagnostic)

**Comment by chrism** [comment]
Hi, I've just been looking at the new diagnostic tool and documentation — it looks amazing 😄👍
