### ISSUE TITLE
ember-copy dependancy 

### ISSUE THREAD

**Issue by gandalfar** [nypublicradio/ember-hifi#54]
Upgrading ember-hifi from 1.15.1 to 1.15.2, I get an error:

`Uncaught Error: Could not find module `ember-copy` imported from `ember-hifi/utils/promise-race``

adding `ember-copy` to my projects `package.json` makes the error go away. Is this correct way to fix this error?

**Comment by m3l1x** [comment]
> Upgrading ember-hifi from 1.15.1 to 1.15.2, I get an error:
> 
> `Uncaught Error: Could not find module `ember-copy`imported from`ember-hifi/utils/promise-race``
> 
> adding `ember-copy` to my projects `package.json` makes the error go away. Is this correct way to fix this error?

+1 same here

**Comment by chrism** [comment]
Just had this same issue.

**Comment by jkeen** [comment]
I moved `ember-copy` to dependencies, so this should be fixed on master, and will be fixed in 1.16. Sorry for letting this stagnate
