### ISSUE TITLE
Can't get duration of hls audio

### ISSUE THREAD

**Issue by dougbanville** [nypublicradio/ember-hifi#55]
Any idea why ember-hifi won't give the duration for a hls file:
https://cdn.rasset.ie/manifest/audio/2018/0917/20180917_rteradio1-ryantubridy-theryantub_cl10935275_10937556_261_/manifest.m3u8

The actual duration is 52 min 17sec

I've tried it with ember-hifi and with nypr-player eg:

{{nypr-player
  sound='https://cdn.rasset.ie/hls-vod/audio/2018/0917/20180917_rteradio1-theraydarcyshow-theraydarc_cl10935280_10937730_261_/20180917_rteradio1-theraydarcyshow-theraydarc_cl10935280_10937730_261_.mp4.m3u8'
  freestanding=true
}}

I plays fine but no duration information

**Comment by dougbanville** [comment]
> @dougbanville Is it in one particular browser, or any browser?

I checked Chrome and Safari

**Comment by jkeen** [comment]
Thanks so much for this report, and sorry for the delay in getting a fix out. Figured out how to determine this with HLS and fixed the issue on master (will be in the 1.16 release)
