### ISSUE TITLE
Support for .stop() in context of live streams

### ISSUE THREAD

**Issue by gandalfar** [nypublicradio/ember-hifi#56]
We switched from MP3 streams to HLS and now live streams won't restart when resuming. With mp3 streams, when I called `.pause()` and then `.play()` it resumed stream from 'current time'. But with HLS streams, it resumes from the point when it was paused.

What I would like to do is 'reload' .m3u8 HLS streams, as they're cached now so I have append a random hash to them so that I can bust ember-hifi's cache.

Would it make sense for `.stop()` to also clear cache so that calling `.play()` would start from a initial state?

If this makes sense, I'm happy to give a try at making pull-request with this changes.

**Comment by zion** [comment]
I just started to use this addon, and this makes a lot of sense. I haven't had a need to fully stop and restart an HLS source but I can see the benefit of clearing the cache when `.stop()` is called. Good idea.

**Comment by jkeen** [comment]
@gandalfar That makes sense to me!

**Comment by jkeen** [comment]
@gandalfar DId you ever take a crack at this PR? I fixed it in #58, but the side effect of stopping the stream is that if the HLS stream has an ad at the start… it'll play it again. 

Try it out with your HLS stream by starting up the dummy app and going to `/diagnostics`

**Comment by gandalfar** [comment]
Thanks, this works great with my HLS stream. Also the diagnostic interface looks great and is very helpful.
