### ISSUE TITLE
Usage in addons

### ISSUE THREAD

**Issue by teejayhh** [nypublicradio/ember-hifi#70]
Hello, I am wondering if this addon works in addons. Usually if an addon like ember-hifi is not included in an app but an addon then we need to move the dependency into the `dependency` section of the addons package.json. Doing this, fails to start up the ember s of the application

```
app1
--- addon1
------ ember-hifi
```

`ember s` (app1) ->
```
~/b/f/a/client git:hifi-test ❯❯❯ ember s                                                   ✭ ✚ ✱
Cannot read property 'connections' of undefined
```

Can anyone anyone confirm this bug?

**Comment by jkeen** [comment]
@teejayhh It definitely does work in addons, as NYPR is using them in many internal addons. https://github.com/nypublicradio/nypr-audio-services/blob/master/package.json

But yeah, looks like currently you've gotta have it in dependencies. Not sure why it's giving you that error. What do you have set in your environment file?

**Comment by teejayhh** [comment]
I am not using it anymore, as it wasn't working for me. I guess we can close this.
