### ISSUE TITLE
Recent Ember version support

### ISSUE THREAD

**Issue by alex-kovalchuk** [nypublicradio/ember-hifi#71]
Hi! Thank you for a great addon, but starting with Ember v3.11, I get this error when trying to play a track:
```
Uncaught Error: Assertion Failed: You attempted to remove a function listener which did not exist on the instance, which means you may have attempted to remove it before it was added.
    at assert (index.js:163)
    at Meta.pushListener (meta.js:542)
    at Meta.removeFromListeners (meta.js:520)
    at removeListener (metal.js:412)
    at Class.off (evented.js:123)
    at Class._unregisterEvents (hifi.js:426)
    at Class._registerEvents (hifi.js:393)
    at hifi.js:235
    at invokeCallback (rsvp.js:490)
    at publish (rsvp.js:473)
```

**Comment by gandalfar** [comment]
@alex-kovalchuk how did you solve this issue?

**Comment by jkeen** [comment]
@gandalfar Are you getting this same error on the latest version of hifi? It's at 3.11 now. Needs some updates, for sure though, just wasn't aware this was still happening.

**Comment by gandalfar** [comment]
@jkeen I'm confused - my package.json and npm tells me that stable is:

`"ember-hifi": "~1.16.0",`

and I'm on ember-hifi 1.16 with Ember 3.17.3

**Comment by gandalfar** [comment]
@jkeen ok, I tasted with checking out version from git and running `yarn link` to it and the problem goes away. I'll check what yarn/npm think about my ember-hifi version and update this comment.

**Comment by jkeen** [comment]
@gandalfar I'll get on doing some updates and cutting a new release! Didn't realize it had been so long

**Comment by gandalfar** [comment]
@jkeen thank you!

**Comment by jkeen** [comment]
@gandalfar released
